### ISSUE TITLE
图片压缩完成后一直处于下载中，无法下载完成

### ISSUE THREAD

**Issue by powercandy** [csj8520/utools-plugin-tinypng#2]
版本1.1.1

步骤：直接将图片拖入tinypng中，

结果：上传完成，压缩完成，下载图片中

多次尝试均是如此，该网络状态下访问  https://tinypng.com/  可以正常压缩下载

**Comment by klwfwdk** [comment]
mac version BigSur 11.4 同样遇到了问题

**Comment by csj8520** [comment]
应该是保存文件的是否出现了错误

我发布了一个新版本 [Releases v1.1.2](https://github.com/csj8520/utools-plugin-tinypng/releases/tag/v1.1.2) (下载upx文件直接拖入utools安装)，

如果还是不行，请下载debug版本把错误信息截图发给我

**Comment by PC-Mo** [comment]
> 应该是保存文件的时候出现了错误
> 
> 我发布了一个新版本 [Releases v1.1.2](https://github.com/csj8520/utools-plugin-tinypng/releases/tag/v1.1.2) (下载upx文件直接拖入utools安装)，
> 
> 如果还是不行，请下载debug版本把错误信息截图发给我

经测试，问题已经修复了

**Comment by powercandy** [comment]
> 应该是保存文件的时候出现了错误
> 
> 我发布了一个新版本 [Releases v1.1.2](https://github.com/csj8520/utools-plugin-tinypng/releases/tag/v1.1.2) (下载upx文件直接拖入utools安装)，
> 
> 如果还是不行，请下载debug版本把错误信息截图发给我

1.1.2版本可以了，谢谢作者大大

**Comment by csj8520** [comment]
utools 插件中心已经发布了，平台还在审核中
